### ISSUE TITLE
issue on win10

### ISSUE THREAD

**Issue by ypLincode** [charlesq34/pointnet#69] opened 2018-01-03 14:34 UTC
When I run the source code, i met the following question:

  File "D:\pointnet\trunk\provider.py", line 88, in getDataFiles
    return [line.rstrip() for line in open(list_filename)]
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\pointnet.git\\trunk\\data/modelnet40_ply_hdf5_2048/train_files.txt'

Any one knows the reason?

**Comment by charlesq34** [comment] 2018-01-09 03:52
Hi @ypLincode 

I think the problem is because Windows uses "\" to separate folders while Linux systems use "/".
You can modify the code as you like to resolve the issue.

Closing the issue now.

**Closed by charlesq34** 2018-01-09 03:52 UTC

**Comment by ypLincode** [comment] 2018-01-29 08:25
@charlesq34 thx

**Comment by taniaCHY** [comment] 2018-06-25 13:30
When I run the source code, i met the following question:
File "h5py\h5f.pyx", line 98, in h5py.h5f.create

OSError: Unable to create file (unable to open file: name = 'data/modelnet40_ply_hdf5_2048/ply_data_train3.h5', errno = 2, error message = 'No such file or directory', flags = 15, o_flags = 502)

**Comment by jainshubham1506** [comment] 2019-03-29 19:44
Issue still exists train data is not being downloaded in windows

**Comment by Meghdadhn** [comment] 2019-06-30 23:57
Same problem here! data folder is empty! Windows 10, Python 3.6

**Comment by bigmpc** [comment] 2019-07-23 15:34
hi, driectly download modelnet40_ply_hdf5_2048.zip file and then create new folder "data" in this folder extract modelnet40_ply_hdf5_2048 file (name of folder most be modelnet40_ply_hdf5_2048 )
folder struct:

-> data
---> modelnet40_ply_hdf5_2048
-------> train_files.txt
-------> test_files.txt
-------> shape_names.txt
-------> etc.
If use winrar open zip file and drop in data folder
![2019-07-23 20_03_47-data](https://user-images.githubusercontent.com/11869014/61725445-0b19b300-ad85-11e9-8487-16155ea5bb8d.png)

**Comment by abbott1234** [comment] 2019-12-31 01:36
How do you running on win10?

**Comment by protactinium91** [comment] 2019-12-31 15:21
> How do you running on win10?

I am running this on Win10, what is not working for you?

**Comment by MeowQiu** [comment] 2020-01-09 12:38
> hi, driectly download modelnet40_ply_hdf5_2048.zip file and then create new folder "data" in this folder extract modelnet40_ply_hdf5_2048 file (name of folder most be modelnet40_ply_hdf5_2048 )
> folder struct:
> 
> -> data
> ---> modelnet40_ply_hdf5_2048
> -------> train_files.txt
> -------> test_files.txt
> -------> shape_names.txt
> -------> etc.
> If use winrar open zip file and drop in data folder
> ![2019-07-23 20_03_47-data](https://user-images.githubusercontent.com/11869014/61725445-0b19b300-ad85-11e9-8487-16155ea5bb8d.png)

Hi,where could i get this zip?

**Comment by bigmpc** [comment] 2020-02-19 06:56
> > hi, driectly download modelnet40_ply_hdf5_2048.zip file and then create new folder "data" in this folder extract modelnet40_ply_hdf5_2048 file (name of folder most be modelnet40_ply_hdf5_2048 )
> > folder struct:
> > -> data
> > ---> modelnet40_ply_hdf5_2048
> > -------> train_files.txt
> > -------> test_files.txt
> > -------> shape_names.txt
> > -------> etc.
> > If use winrar open zip file and drop in data folder
> > ![2019-07-23 20_03_47-data](https://user-images.githubusercontent.com/11869014/61725445-0b19b300-ad85-11e9-8487-16155ea5bb8d.png)
> 
> Hi,where could i get this zip?
In here and 'Download 40-Class Subset'
https://modelnet.cs.princeton.edu/
direct link:
http://modelnet.cs.princeton.edu/ModelNet40.zip

**Comment by MrCrazyCrab** [comment] 2020-11-26 01:39
@protactinium91  how do you compile the ops and run it on windows10? looking for help!

**Comment by bigmpc** [comment] 2020-11-26 02:50
> How do you running on win10?

Yes at that time I was running on Windows 10 (pro version and 64 bit)

**Comment by bigmpc** [comment] 2020-11-26 02:51
> > hi, driectly download modelnet40_ply_hdf5_2048.zip file and then create new folder "data" in this folder extract modelnet40_ply_hdf5_2048 file (name of folder most be modelnet40_ply_hdf5_2048 )
> > folder struct:
> > -> data
> > ---> modelnet40_ply_hdf5_2048
> > -------> train_files.txt
> > -------> test_files.txt
> > -------> shape_names.txt
> > -------> etc.
> > If use winrar open zip file and drop in data folder
> > ![2019-07-23 20_03_47-data](https://user-images.githubusercontent.com/11869014/61725445-0b19b300-ad85-11e9-8487-16155ea5bb8d.png)
> 
> Hi,where could i get this zip?

from here 
http://modelnet.cs.princeton.edu/
[Download 40-Class Subset](http://modelnet.cs.princeton.edu/ModelNet40.zip)

**Comment by bigmpc** [comment] 2020-11-26 02:55
> @protactinium91 how do you compile the ops and run it on windows10? looking for help!

I check the code and found the only part depent on os, is download part. 
so if you download and prepare data for it then you can run with out issue.
more information about how must be dataset:
https://github.com/charlesq34/pointnet/issues/69#issuecomment-514263827
